units:
  - OLE
  - Special Collections
  - Robertson Media Center
  - University of Virginia School of Architecture
  - University of Virginia McIntire Department of Music
  - Women, Gender, and Sexuality Program
  - University of Virginia Department of Spanish, Italian, and Portuguese
  - Claude Moore Health Sciences Library, University of Virginia

identifier_types:
 local: Catalog Key
 oclc: OCLC
 lccn: LCCN
 issue number: Issue Number
 matrix number: Matrix Number
 music publisher: Music Publisher/Label
 videorecording identifier: Videorecording Identifier
 other: Other
note_types:
 general: General Note
 awards: Awards
 biographical/historical: Bibliographical/Historical Note
 creation/production credits: Creation/Production Credits
 language: Language Note
 local: Local Note
 performers: Performers
 statement of responsibility: Statement of Responsibility
 venue: Venue/Event Date
name_types:
  cre: Creator
  act: Actor
  arr: Arranger
  aut: Author
  cmp: Composer
  cnd: Conductor
  cng: Cinematographer
  ctb: Contributor
  drt: Director
  dst: Distributor
  edt: Editor
  hst: Host
  itr: Instrumentalist
  ive: Interviewee
  mod: Moderator
  msd: Musical director
  mus: Musician
  nrt: Narrator
  pan: Panelist
  pre: Presenter
  pro: Producer
  prn: Production Company
  aus: Screenwriter
  sng: Singer
  spk: Speaker
