units:
  - OLE
  - Special Collections
  - Robertson Media Center
  - University of Virginia School of Architecture
  - University of Virginia McIntire Department of Music
  - Women, Gender, and Sexuality Program
  - University of Virginia Department of Spanish, Italian, and Portuguese
  - Claude Moore Health Sciences Library, University of Virginia

identifier_types:
 local: Catalog Key
 oclc: OCLC
 lccn: LCCN
 issue number: Issue Number
 matrix number: Matrix Number
 music publisher: Music Publisher/Label
 videorecording identifier: Videorecording Identifier
 other: Other
note_types:
 general: General Note
 awards: Awards
 biographical/historical: Bibliographical/Historical Note
 creation/production credits: Creation/Production Credits
 language: Language Note
 local: Local Note
 performers: Performers
 statement of responsibility: Statement of Responsibility
 venue: Venue/Event Date
name_types:
  act: Actor
  anm: Animator
  ard: Artistic director
  arr: Arranger
  art: Artist
  aus: Screenwriter
  aut: Author
  chr: Choreographer
  cmp: Composer
  cnd: Conductor
  cng: Cinematographer
  cst: Costume designer
  dnc: Dancer
  drt: Director
  dst: Distributor
  fds: Film distributor
  fld: Field director
  flm: Film editor
  fmd: Film director
  fmk: Filmmaker
  fmp: Film producer
  itr: Instrumentalist
  lyr: Lyricist
  msd: Musical director
  mus: Musician
  nrt: Narrator
  osp: Onscreen presenter
  pan: Panelist
  pre: Presenter
  prf: Performer
  pro: Producer
  rce: Recording engineer
  rcp: Addressee
  rdd: Radio director
  rpc: Radio producer
  sds: Sound designer
  sgd: Stage director
  sng: Singer
  stl: Storyteller
  vac: Voice actor
  vdg: Videographer
  voc: Vocalist
