development:
  administrator:
    - md5wz@virginia.edu
  manager:
    - srv3f@virginia.edu
  group_manager:
    - srv3f@virginia.edu

test:
  administrator:
    - md5wz@virginia.edu
  manager:
    - srv3f@virginia.edu
  group_manager:
    - srv3f@virginia.edu

production:
  administrator:
    - md5wz@virginia.edu
  manager:
    - srv3f@virginia.edu
  group_manager:
    - srv3f@virginia.edu